In [16]:
import csv
data = {}
i = 0;
with open('ArgentinaCPI.csv','r') as f:
    dd = csv.reader(f)
    for record in dd:
        if(i!=0):
            data[float(record[1])] = float(record[2])
        i +=1

In [17]:
data

{1970.0: 1.01,
 1970.25: 1.06,
 1970.5: 1.13,
 1970.75: 1.24,
 1971.0: 1.33,
 1971.25: 1.45,
 1971.5: 1.64,
 1971.75: 1.77,
 1972.0: 2.24,
 1972.25: 2.58,
 1972.5: 2.92,
 1972.75: 3.2,
 1973.0: 4.26,
 1973.25: 4.89,
 1973.5: 4.94,
 1973.75: 5.15,
 1974.0: 5.19,
 1974.25: 5.57,
 1974.5: 6.0,
 1974.75: 6.92,
 1975.0: 8.22,
 1975.25: 10.57,
 1975.5: 19.53,
 1975.75: 28.56,
 1976.0: 45.68,
 1976.25: 85.61,
 1976.5: 101.12,
 1976.75: 131.67,
 1977.0: 171.96,
 1977.25: 209.93,
 1977.5: 267.05,
 1977.75: 355.82,
 1978.0: 466.84,
 1978.25: 606.61,
 1978.5: 744.0,
 1978.75: 950.91,
 1979.0: 1255.96,
 1979.25: 1560.66,
 1979.5: 1999.51,
 1979.75: 2367.83,
 1980.0: 2805.64,
 1980.25: 3328.89,
 1980.5: 3818.9,
 1980.75: 4469.26,
 1981.0: 5115.07,
 1981.25: 6297.67,
 1981.5: 8125.88,
 1981.75: 9952.58,
 1982.0: 12659.68,
 1982.25: 14482.68,
 1982.5: 20789.88,
 1982.75: 30153.65,
 1983.0: 43626.3,
 1983.25: 59885.82,
 1983.5: 91200.11,
 1983.75: 151820.8,
 1984.0: 238465.0,
 1984.25: 394707.2,
 1984

In [18]:
assert data[1970.25] > 1

In [19]:
assert len(data) == 80

In [22]:
import numpy as np

cpi= np.array(list(data.values()))

In [23]:
cpi

array([1.0100000e+00, 1.0600000e+00, 1.1300000e+00, 1.2400000e+00,
       1.3300000e+00, 1.4500000e+00, 1.6400000e+00, 1.7700000e+00,
       2.2400000e+00, 2.5800000e+00, 2.9200000e+00, 3.2000000e+00,
       4.2600000e+00, 4.8900000e+00, 4.9400000e+00, 5.1500000e+00,
       5.1900000e+00, 5.5700000e+00, 6.0000000e+00, 6.9200000e+00,
       8.2200000e+00, 1.0570000e+01, 1.9530000e+01, 2.8560000e+01,
       4.5680000e+01, 8.5610000e+01, 1.0112000e+02, 1.3167000e+02,
       1.7196000e+02, 2.0993000e+02, 2.6705000e+02, 3.5582000e+02,
       4.6684000e+02, 6.0661000e+02, 7.4400000e+02, 9.5091000e+02,
       1.2559600e+03, 1.5606600e+03, 1.9995100e+03, 2.3678300e+03,
       2.8056400e+03, 3.3288900e+03, 3.8189000e+03, 4.4692600e+03,
       5.1150700e+03, 6.2976700e+03, 8.1258800e+03, 9.9525800e+03,
       1.2659680e+04, 1.4482680e+04, 2.0789880e+04, 3.0153650e+04,
       4.3626300e+04, 5.9885820e+04, 9.1200110e+04, 1.5182080e+05,
       2.3846500e+05, 3.9470720e+05, 6.8880360e+05, 1.1963140e

In [24]:
assert 2 >= cpi[0] >= 1
assert cpi.shape == (80,)

In [28]:
def diag(x):
    if x.shape[0] == x.shape[1]:
        return [x[i][i] for i in range(0,len(x))]
    else:
        dim = 0
        if(x.shape[0]<x.shape[1]):
            dim = x.shape[0]
        else:
            dim = x.shape[1]
        return [x[i][i] for i in range(0,dim)]
        

In [26]:
sample = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(diag(sample))

[1, 5, 9]


In [29]:
assert all(diag(sample) == np.array([1, 5, 9]))
assert all(diag(sample[:,0:2]) == np.array([1, 5]))
assert all(diag(sample[1:,:]) == np.array([4, 8]))

In [33]:
cpi.reshape(4,20)

array([[1.0100000e+00, 1.0600000e+00, 1.1300000e+00, 1.2400000e+00,
        1.3300000e+00, 1.4500000e+00, 1.6400000e+00, 1.7700000e+00,
        2.2400000e+00, 2.5800000e+00, 2.9200000e+00, 3.2000000e+00,
        4.2600000e+00, 4.8900000e+00, 4.9400000e+00, 5.1500000e+00,
        5.1900000e+00, 5.5700000e+00, 6.0000000e+00, 6.9200000e+00],
       [8.2200000e+00, 1.0570000e+01, 1.9530000e+01, 2.8560000e+01,
        4.5680000e+01, 8.5610000e+01, 1.0112000e+02, 1.3167000e+02,
        1.7196000e+02, 2.0993000e+02, 2.6705000e+02, 3.5582000e+02,
        4.6684000e+02, 6.0661000e+02, 7.4400000e+02, 9.5091000e+02,
        1.2559600e+03, 1.5606600e+03, 1.9995100e+03, 2.3678300e+03],
       [2.8056400e+03, 3.3288900e+03, 3.8189000e+03, 4.4692600e+03,
        5.1150700e+03, 6.2976700e+03, 8.1258800e+03, 9.9525800e+03,
        1.2659680e+04, 1.4482680e+04, 2.0789880e+04, 3.0153650e+04,
        4.3626300e+04, 5.9885820e+04, 9.1200110e+04, 1.5182080e+05,
        2.3846500e+05, 3.9470720e+05, 6.888036

In [35]:
cpi_mx= cpi.reshape(20,4)
print(cpi.shape)
cpi_mx

(80,)


array([[1.0100000e+00, 1.0600000e+00, 1.1300000e+00, 1.2400000e+00],
       [1.3300000e+00, 1.4500000e+00, 1.6400000e+00, 1.7700000e+00],
       [2.2400000e+00, 2.5800000e+00, 2.9200000e+00, 3.2000000e+00],
       [4.2600000e+00, 4.8900000e+00, 4.9400000e+00, 5.1500000e+00],
       [5.1900000e+00, 5.5700000e+00, 6.0000000e+00, 6.9200000e+00],
       [8.2200000e+00, 1.0570000e+01, 1.9530000e+01, 2.8560000e+01],
       [4.5680000e+01, 8.5610000e+01, 1.0112000e+02, 1.3167000e+02],
       [1.7196000e+02, 2.0993000e+02, 2.6705000e+02, 3.5582000e+02],
       [4.6684000e+02, 6.0661000e+02, 7.4400000e+02, 9.5091000e+02],
       [1.2559600e+03, 1.5606600e+03, 1.9995100e+03, 2.3678300e+03],
       [2.8056400e+03, 3.3288900e+03, 3.8189000e+03, 4.4692600e+03],
       [5.1150700e+03, 6.2976700e+03, 8.1258800e+03, 9.9525800e+03],
       [1.2659680e+04, 1.4482680e+04, 2.0789880e+04, 3.0153650e+04],
       [4.3626300e+04, 5.9885820e+04, 9.1200110e+04, 1.5182080e+05],
       [2.3846500e+05, 3.9470720e+

In [37]:
cpi_d = diag(cpi_mx)

In [39]:
cpi_d

[1.01, 1.45, 2.92, 5.15]

In [40]:
assert cpi_mx.shape == (20, 4)
assert all(cpi_d == np.array([1.01, 1.45, 2.92, 5.15]))

In [41]:
cpi

array([1.0100000e+00, 1.0600000e+00, 1.1300000e+00, 1.2400000e+00,
       1.3300000e+00, 1.4500000e+00, 1.6400000e+00, 1.7700000e+00,
       2.2400000e+00, 2.5800000e+00, 2.9200000e+00, 3.2000000e+00,
       4.2600000e+00, 4.8900000e+00, 4.9400000e+00, 5.1500000e+00,
       5.1900000e+00, 5.5700000e+00, 6.0000000e+00, 6.9200000e+00,
       8.2200000e+00, 1.0570000e+01, 1.9530000e+01, 2.8560000e+01,
       4.5680000e+01, 8.5610000e+01, 1.0112000e+02, 1.3167000e+02,
       1.7196000e+02, 2.0993000e+02, 2.6705000e+02, 3.5582000e+02,
       4.6684000e+02, 6.0661000e+02, 7.4400000e+02, 9.5091000e+02,
       1.2559600e+03, 1.5606600e+03, 1.9995100e+03, 2.3678300e+03,
       2.8056400e+03, 3.3288900e+03, 3.8189000e+03, 4.4692600e+03,
       5.1150700e+03, 6.2976700e+03, 8.1258800e+03, 9.9525800e+03,
       1.2659680e+04, 1.4482680e+04, 2.0789880e+04, 3.0153650e+04,
       4.3626300e+04, 5.9885820e+04, 9.1200110e+04, 1.5182080e+05,
       2.3846500e+05, 3.9470720e+05, 6.8880360e+05, 1.1963140e

In [42]:
cpi[0]

1.01

In [45]:
ratios = [cpi[i]/cpi[i-4] for i in range(4,len(cpi))]
ratios

[1.316831683168317,
 1.3679245283018866,
 1.4513274336283186,
 1.4274193548387097,
 1.6842105263157896,
 1.7793103448275862,
 1.7804878048780488,
 1.807909604519774,
 1.901785714285714,
 1.8953488372093021,
 1.6917808219178083,
 1.609375,
 1.2183098591549297,
 1.1390593047034767,
 1.214574898785425,
 1.3436893203883493,
 1.583815028901734,
 1.8976660682226212,
 3.2550000000000003,
 4.127167630057803,
 5.557177615571776,
 8.09933774834437,
 5.177675371223758,
 4.610294117647059,
 3.7644483362521894,
 2.4521668029435815,
 2.6409216772151898,
 2.7023619655198603,
 2.714817399395208,
 2.889582241699614,
 2.785995131997753,
 2.6724467427350906,
 2.6903435866678094,
 2.5727567959644584,
 2.687513440860215,
 2.4900674091133754,
 2.2338609509857,
 2.1330014224751066,
 1.9099179298928237,
 1.887491922984336,
 1.8231383926662008,
 1.891822799792123,
 2.12780643640839,
 2.2268966227071147,
 2.474976882036805,
 2.2996886149957048,
 2.558477358759913,
 3.0297319890922756,
 3.446082365431038,
 4.134

In [46]:
assert type(ratios)==list
assert len(ratios)==76
assert all(r > 1 for r in ratios)

In [49]:
cpi_s = ['{0:013.2f}'.format(elem) for elem in cpi]

In [50]:
assert all(len(s)==13 for s in cpi_s)
import re
assert all(re.fullmatch(r'\d+\.\d\d', s) for s in cpi_s)
assert all(re.fullmatch(r'^\d.*',s) for s in cpi_s)

In [51]:
cpi_s

['0000000001.01',
 '0000000001.06',
 '0000000001.13',
 '0000000001.24',
 '0000000001.33',
 '0000000001.45',
 '0000000001.64',
 '0000000001.77',
 '0000000002.24',
 '0000000002.58',
 '0000000002.92',
 '0000000003.20',
 '0000000004.26',
 '0000000004.89',
 '0000000004.94',
 '0000000005.15',
 '0000000005.19',
 '0000000005.57',
 '0000000006.00',
 '0000000006.92',
 '0000000008.22',
 '0000000010.57',
 '0000000019.53',
 '0000000028.56',
 '0000000045.68',
 '0000000085.61',
 '0000000101.12',
 '0000000131.67',
 '0000000171.96',
 '0000000209.93',
 '0000000267.05',
 '0000000355.82',
 '0000000466.84',
 '0000000606.61',
 '0000000744.00',
 '0000000950.91',
 '0000001255.96',
 '0000001560.66',
 '0000001999.51',
 '0000002367.83',
 '0000002805.64',
 '0000003328.89',
 '0000003818.90',
 '0000004469.26',
 '0000005115.07',
 '0000006297.67',
 '0000008125.88',
 '0000009952.58',
 '0000012659.68',
 '0000014482.68',
 '0000020789.88',
 '0000030153.65',
 '0000043626.30',
 '0000059885.82',
 '0000091200.11',
 '00001518

In [54]:
filtered_cpi = list(filter(lambda x: re.fullmatch(r'\d{9}[02468].0{2}',x),cpi_s))

In [55]:
assert type(filtered_cpi[0])==str
assert all(re.fullmatch(r'.*\.00', s) for s in filtered_cpi)
assert all(re.fullmatch(r'\d{9}[02468].*', s) for s in filtered_cpi)